version: '3'

services:

  mysql:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ledger
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  web:
    container_name: ledger_scala
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/ledger
    links:
      - mysql